name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzAyNDcwYTAtZWM3YS00NGY5LWIzNmYtZmMxNDA0ZDVkZDBmIiwidGVuYW50X2lkIjoiNTgyYjU1ODI0ZDZlYmI2MDY0OTY1MTA5OTI2ODQ5MjA3OWRjNmJjZjBiZGJkZTdhMDE5NzdmYWU3NzYwOGI1MSIsImludGVybmFsX3NlY3JldCI6ImIxOGFjNTZjLTc0N2EtNGI0Mi1iOTM5LTM4YjM4NDA0MTFjMyJ9.0RCJoaSf_h1c51BaBNVvNMWqq6nB6ggm_LvbwWs0W5A"
JWT_SECRET = "asdasdasd"
